In [16]:
#! python3

import os
os.system("cls")

import numpy as np

mdarray=np.linspace(start=0,stop=10)

print("printing the original element\n",end="\n")
print(mdarray)
print(mdarray.size)
print(mdarray.itemsize,"byte")
print(mdarray.shape)

mdarray=np.linspace(start=0,stop=100,num=30)

print("printing the original element\n",end="\n")
print(mdarray)
print(mdarray.size)
print(mdarray.itemsize,"byte")
print(mdarray.shape)


printing the original element

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]
50
8 byte
(50,)
printing the original element

[  0.           3.44827586   6.89655172  10.34482759  13.79310345
  17.24137931  20.68965517  24.13793103  27.5862069   31.03448276
  34.48275862  37.93103448  41.37931034  44.82758621  48.27586207
  51.72413793  55.17241379  58.62068966  62.06896552  65.51724138
  68.96551724  72.4137931   75.86206897  79.3103

In [19]:
#! python3

import os
os.system("cls")

import numpy as np

mdarray=np.linspace(start=0,stop=1,num=55)

print("printing the original element\n",end="\n")
print(mdarray)
print(mdarray.size)
print(mdarray.itemsize,"byte")
print(mdarray.shape)

printing the original element

[0.         0.01851852 0.03703704 0.05555556 0.07407407 0.09259259
 0.11111111 0.12962963 0.14814815 0.16666667 0.18518519 0.2037037
 0.22222222 0.24074074 0.25925926 0.27777778 0.2962963  0.31481481
 0.33333333 0.35185185 0.37037037 0.38888889 0.40740741 0.42592593
 0.44444444 0.46296296 0.48148148 0.5        0.51851852 0.53703704
 0.55555556 0.57407407 0.59259259 0.61111111 0.62962963 0.64814815
 0.66666667 0.68518519 0.7037037  0.72222222 0.74074074 0.75925926
 0.77777778 0.7962963  0.81481481 0.83333333 0.85185185 0.87037037
 0.88888889 0.90740741 0.92592593 0.94444444 0.96296296 0.98148148
 1.        ]
55
8 byte
(55,)


In [26]:
#! python3

import os
os.system("cls")

import numpy as np

mdarray=np.linspace(start=1,stop=5,num=100,endpoint=False)

print("printing the original element\n",end="\n")
print(mdarray)

printing the original element

[1.   1.04 1.08 1.12 1.16 1.2  1.24 1.28 1.32 1.36 1.4  1.44 1.48 1.52
 1.56 1.6  1.64 1.68 1.72 1.76 1.8  1.84 1.88 1.92 1.96 2.   2.04 2.08
 2.12 2.16 2.2  2.24 2.28 2.32 2.36 2.4  2.44 2.48 2.52 2.56 2.6  2.64
 2.68 2.72 2.76 2.8  2.84 2.88 2.92 2.96 3.   3.04 3.08 3.12 3.16 3.2
 3.24 3.28 3.32 3.36 3.4  3.44 3.48 3.52 3.56 3.6  3.64 3.68 3.72 3.76
 3.8  3.84 3.88 3.92 3.96 4.   4.04 4.08 4.12 4.16 4.2  4.24 4.28 4.32
 4.36 4.4  4.44 4.48 4.52 4.56 4.6  4.64 4.68 4.72 4.76 4.8  4.84 4.88
 4.92 4.96]


In [33]:
#! python3

import os
os.system("cls")

import numpy as np

mdarray=np.linspace(start=1,stop=5,num=100,dtype=int,endpoint=False)

print("printing the original element\n",end="\n")
print(mdarray)

printing the original element

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4]


In [39]:
# for interval
import numpy as np

mdarray=np.arange(1,10)
print(mdarray)
mdarray=np.arange(10)
print(mdarray)
mdarray=np.arange(1,10,2)#stepup 2
print(mdarray)




[1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [3]:
import numpy as np

mdarray=np.arange(10)
print(mdarray)
print(mdarray+.5)
print(mdarray+.25)
print(mdarray+.75)
print(mdarray+5.05)

[0 1 2 3 4 5 6 7 8 9]
[0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
[0.25 1.25 2.25 3.25 4.25 5.25 6.25 7.25 8.25 9.25]
[0.75 1.75 2.75 3.75 4.75 5.75 6.75 7.75 8.75 9.75]
[ 5.05  6.05  7.05  8.05  9.05 10.05 11.05 12.05 13.05 14.05]


In [9]:
import numpy as np

mdarray=np.arange(17)
print(mdarray)
print("after subtract 0.5 from data is \n",mdarray-.5)
print("after subtract 0.25 from data is \n",mdarray-.25)
print("after subtract 0.75 from data is \n",mdarray-.75)
print("after subtract 5.05 from data is \n",mdarray-5.05)

print("after division 0.5 from data is \n",mdarray/.5)
print("after division 0.25 from data is \n",mdarray/.25)
print("after division 0.75 from data is \n",mdarray/.75)
print("after division 5.05 from data is \n",mdarray/5.05)

print("after modulus 0.5 from data is \n",mdarray%.5)
print("after modulus 0.25 from data is \n",mdarray%.25)
print("after modulus 0.75 from data is \n",mdarray%.75)
print("after modulus 5.05 from data is \n",mdarray%5.05)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
after subtract 0.5 from data is 
 [-0.5  0.5  1.5  2.5  3.5  4.5  5.5  6.5  7.5  8.5  9.5 10.5 11.5 12.5
 13.5 14.5 15.5]
after subtract 0.25 from data is 
 [-0.25  0.75  1.75  2.75  3.75  4.75  5.75  6.75  7.75  8.75  9.75 10.75
 11.75 12.75 13.75 14.75 15.75]
after subtract 0.75 from data is 
 [-0.75  0.25  1.25  2.25  3.25  4.25  5.25  6.25  7.25  8.25  9.25 10.25
 11.25 12.25 13.25 14.25 15.25]
after subtract 5.05 from data is 
 [-5.05 -4.05 -3.05 -2.05 -1.05 -0.05  0.95  1.95  2.95  3.95  4.95  5.95
  6.95  7.95  8.95  9.95 10.95]
after division 0.5 from data is 
 [ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32.]
after division 0.25 from data is 
 [ 0.  4.  8. 12. 16. 20. 24. 28. 32. 36. 40. 44. 48. 52. 56. 60. 64.]
after division 0.75 from data is 
 [ 0.          1.33333333  2.66666667  4.          5.33333333  6.66666667
  8.          9.33333333 10.66666667 12.         13.33333333 14.66666667
 16.         17

In [16]:
# over loading of operator

#! python3

import os
os.system("cls")

import numpy as np

msarray= np.arange(10)
print(msarray)
print("the array is \n")
msarray *=2
print("after multiplaying 2 in each element\n")
print(msarray)
print(sum(msarray))


[0 1 2 3 4 5 6 7 8 9]
the array is 

after multiplaying 2 in each element

[ 0  2  4  6  8 10 12 14 16 18]
90


In [20]:
#! python3

import os
os.system("cls")
import numpy as np
mdarray=np.arange(1,10).reshape(3,3)
print("the data in array")
print(mdarray)

print("the data of array in transposal format\n")
print(mdarray.T)

the data in array
[[1 2 3]
 [4 5 6]
 [7 8 9]]
the data of array in transposal format

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [26]:
#! python3

import os
os.system("cls")
import numpy as np
mdarray=np.arange(1,10)
print("the data in array")
print(mdarray)

print("the max data of array \n")
print(mdarray.max())

print("the min data of array \n")
print(mdarray.min())


the data in array
[1 2 3 4 5 6 7 8 9]
the max data of array 

9
the min data of array 

1


In [20]:
#! python3

import os
os.system("cls")
import numpy as np
mdarray=np.arange(1,10)
print("the data in array")
print(mdarray)

search=int(input("enter the aray data to search "))
print("searching......search complited ")
surchresult=np.where(mdarray==search)
print(str(surchresult).replace("(array([","the index no is : ").replace("], dtype=int64),)",""))



the data in array
[1 2 3 4 5 6 7 8 9]
enter the aray data to search 33
searching......search complited 
the index no is : 


In [28]:
# search index no from 
#! python3

import os
os.system("cls")
import numpy as np
mdarray=np.arange(1,22).reshape(3,7)
print("the data in array")
print(mdarray)

search=int(input("enter the aray data to search "))
print("searching......search complited ")
surchresult=np.where(mdarray==search)
print(str(surchresult).replace("(array([","The index no is : ").replace("], dtype=int64), array([",",").replace("], dtype=int64))",""))


the data in array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
enter the aray data to search 77
searching......search complited 
The index no is : ,


In [35]:




# search index no from 
#! python3

import os
os.system("cls")
import numpy as np
mdarray=np.linspace(start=0,stop=29,num=21).reshape(3,7)
print("the data in array\n")
print(mdarray)

search=int(input("\nenter the aray data to search "))
print("searching......search complited ")
surchresult=np.where(mdarray==search)
print("\n"+str(surchresult).replace("(array([","The index no is : ").replace("], dtype=int64), array([",",").replace("], dtype=int64))",""))


the data in array

[[ 0.    1.45  2.9   4.35  5.8   7.25  8.7 ]
 [10.15 11.6  13.05 14.5  15.95 17.4  18.85]
 [20.3  21.75 23.2  24.65 26.1  27.55 29.  ]]

enter the aray data to search 3
searching......search complited 

The index no is : ,


In [42]:

# indices of element
# search index no from 
#! python3

import os
os.system("cls")
import numpy as np
mdarray=np.arange(1,22).reshape(3,7)
print("the data in array")
print(mdarray)


print("searching......search complited ")
surchresult=np.where(mdarray==np.max(mdarray))
print(surchresult)
print(str(surchresult).replace("(array([","The max index no is : ").replace("], dtype=int64), array([",",").replace("], dtype=int64))",""))


the data in array
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]
searching......search complited 
(array([2], dtype=int64), array([6], dtype=int64))
The max index no is : 2,6


In [43]:
# indices of element
#! python3

import os
os.system("cls")
import numpy as np
mdarray=np.arange(1,22).reshape(3,7)
print("the data in array")
print(mdarray)


print("searching......search complited ")
surchresult=np.where(mdarray==np.min(mdarray))
print(surchresult)
print(str(surchresult).replace("(array([","The min data index no is : ").replace("], dtype=int64), array([",",").replace("], dtype=int64))",""))


the data in array
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]
searching......search complited 
(array([0], dtype=int64), array([0], dtype=int64))
The min data index no is : 0,0


In [50]:
# indices of element
#! python3

import os
os.system("cls")
import numpy as np
mdarray=np.arange(1,22).reshape(3,7)
print("the data in array")
print(mdarray)

print("\n\nthe data in array after transpose\n")
transposemdarray=mdarray.T
print(transposemdarray)

surchresulttranspose=np.where(transposemdarray==search)

search=int(input("\nenter the aray data to search "))
surchresult=np.where(mdarray==search)

print("searching......search complited ")
print("the index no of '"+str(search)+"' is  ")
print(str(surchresult).replace("(array([","The index no is : ").replace("], dtype=int64), array([",",").replace("], dtype=int64))",""))

print(str(surchresulttranspose).replace("(array([","The index no after transpose is : ").replace("], dtype=int64), array([",",").replace("], dtype=int64))",""))


the data in array
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]


the data in array after transpose

[[ 1  8 15]
 [ 2  9 16]
 [ 3 10 17]
 [ 4 11 18]
 [ 5 12 19]
 [ 6 13 20]
 [ 7 14 21]]

enter the aray data to search 9
searching......search complited 
the index no of '9' is  
The index no is : 1,1
The index no after transpose is : 6,0


In [56]:
#row wise highest element
# axis 0=column (X axis)
# axis 1=row (Y axis)

#! python3
import os
os.system("cls")

import numpy as np

mdarray=np.arange(5,45).reshape(8,5)
print(mdarray)
print("The max element in row wise is : ",mdarray.max(axis=1))
print("The min element in row wise is : ",mdarray.min(axis=1))
print("\n")

print("The max element in column wise is : ",mdarray.max(axis=0))
print("The min element in column wise is : ",mdarray.min(axis=0))




[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]]
The max element in row wise is :  [ 9 14 19 24 29 34 39 44]
The min element in row wise is :  [ 5 10 15 20 25 30 35 40]


The max element in column wise is :  [40 41 42 43 44]
The min element in column wise is :  [5 6 7 8 9]


In [6]:
# indices of element
#! python3
import os
os.system("cls")

import numpy as np
mdarray=np.array([[ 5 , 6 , 2 , 8 , 1],[10 ,11 ,10 ,13 ,18],[15, 12, 17, 1 ,3],
 [20 ,21 ,22 ,2 ,7],
 [25 ,99 ,27 ,28 ,9],
 [75 ,31 ,32 ,33 ,4],
 [35 ,99 ,37 ,38 ,8],
 [40 ,77 ,42 ,77 ,44]])

print("the element of array is \n",mdarray,end="\n\n")
print("the element of array after transpose\n",mdarray.T,end="\n")

print("the max element of normal array is ",np.max(mdarray))

print("the index no for the max no in normal array is ",np.where(mdarray==np.max(mdarray)))
print("the index no for the max no in normal array is ",np.where(mdarray.T==np.max(mdarray.T)),end="\n")

print("the largest element in row wise ",mdarray.max(axis=1))
print("the largest element in colmn wise ",mdarray.max(axis=0),end="\n")

print("the smalest element in row wise ",mdarray.min(axis=1))
print("the smalest element in column wise ",mdarray.min(axis=0))

print("the largest element in row wise in transpose aray ",mdarray.T.max(axis=1))
print("the largest element in colmn wise in transpose aray ",mdarray.T.max(axis=0),end="\n")

print("the smalest element in row wise in transpose aray ",mdarray.T.min(axis=1))
print("the smalest element in column wise in transpose aray ",mdarray.T.min(axis=0))



the element of array is 
 [[ 5  6  2  8  1]
 [10 11 10 13 18]
 [15 12 17  1  3]
 [20 21 22  2  7]
 [25 99 27 28  9]
 [75 31 32 33  4]
 [35 99 37 38  8]
 [40 77 42 77 44]]

the element of array after transpose
 [[ 5 10 15 20 25 75 35 40]
 [ 6 11 12 21 99 31 99 77]
 [ 2 10 17 22 27 32 37 42]
 [ 8 13  1  2 28 33 38 77]
 [ 1 18  3  7  9  4  8 44]]
the max element of normal array is  99
the index no for the max no in normal array is  (array([4, 6], dtype=int64), array([1, 1], dtype=int64))
the index no for the max no in normal array is  (array([1, 1], dtype=int64), array([4, 6], dtype=int64))
the largest element in row wise  [ 8 18 17 22 99 75 99 77]
the largest element in colmn wise  [75 99 42 77 44]
the smalest element in row wise  [ 1 10  1  2  9  4  8 40]
the smalest element in column wise  [5 6 2 1 1]
the largest element in row wise in transpose aray  [75 99 42 77 44]
the largest element in colmn wise in transpose aray  [ 8 18 17 22 99 75 99 77]
the smalest element in row wise in trans

In [14]:
#find the INDEX NO OF MAX OR MIN VALUE 
#! python3

import os 
os.system("cls")

import numpy as np
mdarray=np.array([[ 5 , 6 , 2 , 8 , 1],[10 ,11 ,10 ,13 ,18],[15, 12, 17, 1 ,3],
 [20 ,21 ,22 ,2 ,7],
 [1 ,99 ,27 ,28 ,9],
 [75 ,1 ,32 ,33 ,4],
 [35 ,99 ,37 ,4 ,8],
 [40 ,77 ,42 ,77 ,44]])

print("\nthe element of array\n",mdarray)
print("\nthe element in max value in row wise ",mdarray.max(axis=1))
print("\nthe index no of max value in row wise ",np.argmax(mdarray,axis=1))
print("\nthe element in min value in row wise ",mdarray.min(axis=1))
print("\nthe index no of min value in row wise ",np.argmin(mdarray,axis=1))

print("---------------------------------------------------------------")
print("\nthe element in max value in column wise ",mdarray.max(axis=0))
print("\nthe index no of max value in column wise ",np.argmax(mdarray,axis=0))
print("\nthe element in min value in column wise ",mdarray.min(axis=0))
print("\nthe index no of min value in column wise ",np.argmin(mdarray,axis=0))





the element of array
 [[ 5  6  2  8  1]
 [10 11 10 13 18]
 [15 12 17  1  3]
 [20 21 22  2  7]
 [ 1 99 27 28  9]
 [75  1 32 33  4]
 [35 99 37  4  8]
 [40 77 42 77 44]]

the element in max value in row wise  [ 8 18 17 22 99 75 99 77]

the index no of max value in row wise  [3 4 2 2 1 0 1 1]

the element in min value in row wise  [ 1 10  1  2  1  1  4 40]

the index no of min value in row wise  [4 0 3 3 0 1 3 0]
---------------------------------------------------------------

the element in max value in column wise  [75 99 42 77 44]

the index no of max value in column wise  [5 4 7 7 7]

the element in min value in column wise  [1 1 2 1 1]

the index no of min value in column wise  [4 5 0 2 0]


In [23]:
#! python3

import os
os.system("cls")

import numpy as np
mdarray=np.array([[ 5 , 6 , 2 , 8 , 1],[10 ,11 ,10 ,13 ,18],[15, 12, 17, 1 ,3],
 [20 ,21 ,22 ,2 ,7],
 [1 ,99 ,27 ,28 ,9],
 [75 ,1 ,32 ,33 ,4],
 [35 ,99 ,37 ,4 ,8],
 [40 ,77 ,42 ,77 ,44]])

print("the element of array is\n",mdarray,end="\n\n")
print("the sum of element on row wise : ",mdarray.sum(axis=1))
print("the sum of element on column wise : ",mdarray.sum(axis=0))

print("the sum of all element : ",np.sum(mdarray))
print("the cumulative sum of all element or array : ",mdarray.cumsum())
print("the cumulative sum of element on row wise : \n",mdarray.cumsum(axis=1))
print("the cumulative sum of element on column wise : \n",mdarray.cumsum(axis=0))






the element of array is
 [[ 5  6  2  8  1]
 [10 11 10 13 18]
 [15 12 17  1  3]
 [20 21 22  2  7]
 [ 1 99 27 28  9]
 [75  1 32 33  4]
 [35 99 37  4  8]
 [40 77 42 77 44]]

the sum of element on row wise :  [ 22  62  48  72 164 145 183 280]
the sum of element on column wise :  [201 326 189 166  94]
the sum of all element :  976
the cumulative sum of all element or array :  [  5  11  13  21  22  32  43  53  66  84  99 111 128 129 132 152 173 195
 197 204 205 304 331 359 368 443 444 476 509 513 548 647 684 688 696 736
 813 855 932 976]
the cumulative sum of element on row wise : 
 [[  5  11  13  21  22]
 [ 10  21  31  44  62]
 [ 15  27  44  45  48]
 [ 20  41  63  65  72]
 [  1 100 127 155 164]
 [ 75  76 108 141 145]
 [ 35 134 171 175 183]
 [ 40 117 159 236 280]]
the cumulative sum of element on column wise : 
 [[  5   6   2   8   1]
 [ 15  17  12  21  19]
 [ 30  29  29  22  22]
 [ 50  50  51  24  29]
 [ 51 149  78  52  38]
 [126 150 110  85  42]
 [161 249 147  89  50]
 [201 326 189 166  94

In [29]:
#! python3

import os
os.system("cls")

import numpy as np
fastarray= np.array([[90,43,22,51],[34,66,41,38],[9,6,2,5]])
secondarray= np.array([[70,4,2,1],[3,6,1,68],[89,26,32,54]])

print("the element of fast array is \n",fastarray)
print("the element of second array is \n",secondarray)

combinearray=fastarray + secondarray
print("the element after join two array is \n",combinearray)
suntractarray=fastarray - secondarray
print("the element after substract second array from fast array is \n",suntractarray)





the element of fast array is 
 [[90 43 22 51]
 [34 66 41 38]
 [ 9  6  2  5]]
the element of second array is 
 [[70  4  2  1]
 [ 3  6  1 68]
 [89 26 32 54]]
the element after join two array is 
 [[160  47  24  52]
 [ 37  72  42 106]
 [ 98  32  34  59]]
the element after substract second array from fast array is 
 [[ 20  39  20  50]
 [ 31  60  40 -30]
 [-80 -20 -30 -49]]


In [31]:
# array multiplication

#! python3

import os
os.system("cls")

import numpy as np
fastarray= np.array([[90,43,22,51],[34,66,41,38],[9,6,2,5]])
secondarray= np.array([[70,4,2,1],[3,6,1,68],[89,26,32,54]])

multiplicationarray=fastarray*secondarray
print("the fast array\n",fastarray)
print("the second array\n",secondarray)
print("the multiplication of array is \n",multiplicationarray)


the fast array
 [[90 43 22 51]
 [34 66 41 38]
 [ 9  6  2  5]]
the second array
 [[70  4  2  1]
 [ 3  6  1 68]
 [89 26 32 54]]
the multiplication of array is 
 [[6300  172   44   51]
 [ 102  396   41 2584]
 [ 801  156   64  270]]


In [37]:
# matrix multiplication 
# use n x n matrix 
#! python3

import os
os.system("cls")

import numpy as np
fastarray= np.array([[90,43,22,51],[34,66,41,38],[9,6,2,5],[1,1,1,1]])
secondarray= np.array([[70,4,2,1],[3,6,1,68],[89,26,32,54],[1,1,1,1]])


print("the fast array\n",fastarray)
print("the second array\n",secondarray)
print("the matrix multiplication is ",fastarray.dot(secondarray))



the fast array
 [[90 43 22 51]
 [34 66 41 38]
 [ 9  6  2  5]
 [ 1  1  1  1]]
the second array
 [[70  4  2  1]
 [ 3  6  1 68]
 [89 26 32 54]
 [ 1  1  1  1]]
the matrix multiplication is  [[8438 1241  978 4253]
 [6265 1636 1484 6774]
 [ 831  129   93  530]
 [ 163   37   36  124]]


In [39]:
# sin value 

import os
os.system("cls")

import numpy as np
fastarray= np.array([[90,43,22,51],[34,66,41,38],[9,6,2,5],[1,1,1,1]])

print("the element of array is \n",fastarray)
print("the sin value of matrix is \n",np.sin(fastarray))


the element of array is 
 [[90 43 22 51]
 [34 66 41 38]
 [ 9  6  2  5]
 [ 1  1  1  1]]
the sin value of matrix is 
 [[ 0.89399666 -0.83177474 -0.00885131  0.67022918]
 [ 0.52908269 -0.02655115 -0.15862267  0.29636858]
 [ 0.41211849 -0.2794155   0.90929743 -0.95892427]
 [ 0.84147098  0.84147098  0.84147098  0.84147098]]


In [42]:
# exponnanttial 

#! python3

import os
os.system("cls")

import numpy as np
fastarray= np.array([[90,43,22,51],[34,66,41,38],[9,6,2,5],[1,1,1,1]])

print("the element of array is \n",fastarray)

print("the expnantial data is \n",np.exp(fastarray))


the element of array is 
 [[90 43 22 51]
 [34 66 41 38]
 [ 9  6  2  5]
 [ 1  1  1  1]]
the expnantial data is 
 [[1.22040329e+39 4.72783947e+18 3.58491285e+09 1.40934908e+22]
 [5.83461743e+14 4.60718663e+28 6.39843494e+17 3.18559318e+16]
 [8.10308393e+03 4.03428793e+02 7.38905610e+00 1.48413159e+02]
 [2.71828183e+00 2.71828183e+00 2.71828183e+00 2.71828183e+00]]


In [43]:
# square root valu
#! python3

import os
os.system("cls")

import numpy as np
fastarray= np.array([[90,43,22,51],[34,66,41,38],[9,6,2,5],[1,1,1,1]])

print("the element of array is \n",fastarray)

print("the squareroot data is \n",np.sqrt(fastarray))


the element of array is 
 [[90 43 22 51]
 [34 66 41 38]
 [ 9  6  2  5]
 [ 1  1  1  1]]
the squareroot data is 
 [[9.48683298 6.55743852 4.69041576 7.14142843]
 [5.83095189 8.1240384  6.40312424 6.164414  ]
 [3.         2.44948974 1.41421356 2.23606798]
 [1.         1.         1.         1.        ]]


In [44]:
# standard deviation
#! python3

import os
os.system("cls")

import numpy as np
fastarray= np.array([[90,43,22,51],[34,66,41,38],[9,6,2,5],[1,1,1,1]])

print("the element of array is \n",fastarray)

print("the standard deviation data is \n",np.std(fastarray))



the element of array is 
 [[90 43 22 51]
 [34 66 41 38]
 [ 9  6  2  5]
 [ 1  1  1  1]]
the standard deviation data is 
 26.53233581405904


In [46]:
# concat vartically two string

#! python3

import os
os.system("cls")

import numpy as np
fastarray= np.array([[90,43,22,51],[34,66,41,38],[9,6,2,5],[1,1,1,1]])
secondarray= np.array([[70,4,2,1],[3,6,1,68],[89,26,32,54],[1,1,1,1]])


print("the fast array is\n",fastarray)
print("the second array is\n",secondarray)

print("the concatination of string is \n",np.vstack((fastarray,secondarray))) #vartically concat


the fast array is
 [[90 43 22 51]
 [34 66 41 38]
 [ 9  6  2  5]
 [ 1  1  1  1]]
the second array is
 [[70  4  2  1]
 [ 3  6  1 68]
 [89 26 32 54]
 [ 1  1  1  1]]
the concatination of string is 
 [[90 43 22 51]
 [34 66 41 38]
 [ 9  6  2  5]
 [ 1  1  1  1]
 [70  4  2  1]
 [ 3  6  1 68]
 [89 26 32 54]
 [ 1  1  1  1]]


In [47]:
# concat horizentally two string

#! python3

import os
os.system("cls")

import numpy as np
fastarray= np.array([[90,43,22,51],[34,66,41,38],[9,6,2,5],[1,1,1,1]])
secondarray= np.array([[70,4,2,1],[3,6,1,68],[89,26,32,54],[1,1,1,1]])


print("the fast array is\n",fastarray)
print("the second array is\n",secondarray)

print("the concatination of string is \n",np.hstack((fastarray,secondarray))) #vartically concat

the fast array is
 [[90 43 22 51]
 [34 66 41 38]
 [ 9  6  2  5]
 [ 1  1  1  1]]
the second array is
 [[70  4  2  1]
 [ 3  6  1 68]
 [89 26 32 54]
 [ 1  1  1  1]]
the concatination of string is 
 [[90 43 22 51 70  4  2  1]
 [34 66 41 38  3  6  1 68]
 [ 9  6  2  5 89 26 32 54]
 [ 1  1  1  1  1  1  1  1]]


In [21]:
import numpy
dir(numpy)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad