In [44]:
#! python3
# > big endian notation
# < little endian notation

import os
os.system("cls")

import numpy as np
ff=np.array([[1,4],[8,7],[88,7]])
mydatatype=np.dtype('>i4')
print("the byte order of the data type is ",mydatatype.byteorder)
print("the size of datatype is ",mydatatype.itemsize)
print("the data type is ",mydatatype.name)
print("the calass of data type ",type(mydatatype))

the byte order of the data type is  >
the size of datatype is  4
the data type is  int32
the calass of data type  <class 'numpy.dtype'>


In [2]:
#! python3

import os
os.system("cls")

import numpy as np

mystudentdatatype=np.dtype([('student name',np.unicode_,40),('student grade',np.float64,(2))])

print("the data type of ",mystudentdatatype['student name'])
print("the data type of ",mystudentdatatype['student grade'])

mydatatype=np.array([('alok kumar behera',(9.26,8.35)),('rakesh kumar ss',(8.36,9.45))],dtype=mystudentdatatype)

print("the fast student is : ",mydatatype[0])
print("the second student is : ",mydatatype[1])

the data type of  <U40
the data type of  ('<f8', (2,))
the fast student is :  ('alok kumar behera', [9.26, 8.35])
the second student is :  ('rakesh kumar ss', [8.36, 9.45])


In [4]:
#! python3

import os
os.system("cls")

import numpy as np

mystudentdatatype=np.dtype([('student name',np.unicode_,40),('student grade',np.float64,(2))])

print("the data type of ",mystudentdatatype['student name'])
print("the data type of ",mystudentdatatype['student grade'])

mydatatype=np.array([('alok kumar behera',(9.26,8.35)),('rakesh kumar ss',(8.36,9.45))],dtype=mystudentdatatype)

print("the student is : ",mydatatype['student name'])
print("the student grade is : ",mydatatype['student grade'])

the data type of  <U40
the data type of  ('<f8', (2,))
the student is :  ['alok kumar behera' 'rakesh kumar ss']
the student grade is :  [[9.26 8.35]
 [8.36 9.45]]


In [10]:
#! python3

import os
os.system("cls")

import numpy as np

mystudentdatatype=np.dtype([('student name',np.unicode_,40),('student grade',np.float64,(2))])

print("the data type of ",mystudentdatatype['student name'])
print("the data type of ",mystudentdatatype['student grade'])

mydatatype=np.array([('alok kumar behera',(9.26,8.35)),('rakesh kumar ss',(8.36,9.45))],dtype=mystudentdatatype)

print("the student is : ",mydatatype['student name'])
print("the student grade is : ",mydatatype['student grade'])

print("the data in 0 index ",mydatatype[0]['student name'])
print("the data in 0 index ",mydatatype[0]['student grade'])

the data type of  <U40
the data type of  ('<f8', (2,))
the student is :  ['alok kumar behera' 'rakesh kumar ss']
the student grade is :  [[9.26 8.35]
 [8.36 9.45]]
the data in 0 index  alok kumar behera
the data in 0 index  [9.26 8.35]


In [4]:
# it gives garbage value
#! python3

import os
os.system("cls")

import numpy as np

myarray=np.empty((3,4),dtype=int)
myarray

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [6]:
#! python3

import os
os.system("cls")

import numpy as np

myarray=np.zeros((3,4),dtype=int)
myarray

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [7]:
#! python3

import os
os.system("cls")

import numpy as np

myarray=np.ones((3,4),dtype=int)
myarray

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])